language: java

jdk:
  - oraclejdk8

install: mvn install -DskipTests=true -Dgpg.skip=true -B -V

script:
  mvn clean test package

deploy:
  provider: releases
  user: "Max-Morozov"
  password: "newpassword123"
  file: "target/digitized-school-1.0.jar"
  skip_cleanup: true
  on:
    tags: true

branches:
  only:
    - master

notifications:
  slack:
    rooms:
      - kpi-integration-2016:zvKvQcOYpf5YKTKXeIyl9Tzs#dreamteam
