language: java
jdk:
  - oraclejdk8
install: mvn install -DskipTests=true -Dgpg.skip=true
script: mvn clean package

branches:
  only:
    - master

notifications:
  slack:
    rooms:
      - kpi-integration-2016:zvKvQcOYpf5YKTKXeIyl9Tzs#dreamteam