language: java
jdk:
  - oraclejdk8
install: mvn install -DskipTests=true -Dgpg.skip=true -B -V
script:
  mvn clean package test
  after_success:
    - chmod a+x deploy.sh
    - ./deploy.sh
branches:
  only:
    - master

notifications:
  slack:
    rooms:
      - kpi-integration-2016:zvKvQcOYpf5YKTKXeIyl9Tzs#dreamteam