sudo: required

language: java

services:
  - docker

jdk:
  - oraclejdk8

before_install:
   - docker -t build "digitized-school" .
   - docker run --name demo-mysql -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=demo -e MYSQL_USER=demo_user -e MYSQL_PASSWORD=demo_pass -d mysql:5.6
   - docker run -p 8080:8080 --name demo-app --link demo-mysql:mysql -d digitized-school
   - docker ps -a
   - docker logs demo-app

install: mvn install -DskipTests=true -Dgpg.skip=true -B -V

script:
  mvn package

branches:
  only:
    - master

notifications:
  slack:
    rooms:
      - kpi-integration-2016:zvKvQcOYpf5YKTKXeIyl9Tzs#dreamteam
