language: java
jdk:
  - oraclejdk8
install: mvn install -DskipTests=true -Dgpg.skip=true -B -V
script:
  mvn clean package test
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'

branches:
  only:
    - master

notifications:
  slack:
    rooms:
      - kpi-integration-2016:zvKvQcOYpf5YKTKXeIyl9Tzs#dreamteam